import type { Equipment } from "@appTypes/Equipment/Equipment";

export interface TemplateDefinition {
  label: string;
  value: string;
  data: Partial<Equipment>;
}

export const EQUIPMENT_TEMPLATES: TemplateDefinition[] = [
  {
    label: "⚔️ Melee Weapon (Longsword)",
    value: "melee-longsword",
    data: {
      name: "Longsword",
      tier: "Common",
      weight: 3,
      cost: { quantity: 15, unit: "gp" },
      damage: { damageDice: "1d8", damageType: { name: "Slashing" } },
      range: { normal: 5, long: 0 },
      tags: ["weapon", "melee", "versatile"],
      description: ["A versatile martial melee weapon.", "Deals 1d8 slashing damage (one-handed) or 1d10 slashing damage (two-handed)."],
      isCustom: true,
      isDeleted: false,
    },
  },
  {
    label: "🏹 Ranged Weapon (Shortbow)",
    value: "ranged-shortbow",
    data: {
      name: "Shortbow",
      tier: "Common",
      weight: 2,
      cost: { quantity: 25, unit: "gp" },
      damage: { damageDice: "1d6", damageType: { name: "Piercing" } },
      range: { normal: 80, long: 320 },
      tags: ["weapon", "ranged", "ammunition", "two-handed"],
      description: ["A simple ranged weapon.", "It has a normal range of 80 feet, and a long range of 320 feet. It requires arrows and two hands to shoot."],
      isCustom: true,
      isDeleted: false,
    },
  },
  {
    label: "🧪 Potion of Healing (Consumable)",
    value: "potion-healing",
    data: {
      name: "Potion of Healing",
      tier: "Common",
      weight: 0.5,
      cost: { quantity: 50, unit: "gp" },
      tags: ["potion", "consumable", "healing", "magical"],
      description: ["A character who drinks the magical red fluid in this vial regains 2d4 + 2 hit points.", "Drinking or administering a potion takes an action."],
      isCustom: true,
      isDeleted: false,
    },
  },
  {
    label: "📜 Spell Scroll (Consumable)",
    value: "spell-scroll",
    data: {
      name: "Spell Scroll (1st Level)",
      tier: "Common",
      weight: 0.1,
      cost: { quantity: 50, unit: "gp" },
      tags: ["scroll", "consumable", "magic", "utility"],
      description: ["A scroll bears the words of a single spell, written in mystical cipher.", "If the spell is on your class's spell list, you can read the scroll and cast its spell without providing any material components."],
      isCustom: true,
      isDeleted: false,
    },
  },
  {
    label: "🛡️ Standard Shield (Armor)",
    value: "armor-shield",
    data: {
      name: "Shield",
      tier: "Common",
      weight: 6,
      cost: { quantity: 10, unit: "gp" },
      tags: ["armor", "shield", "defense"],
      description: ["A standard wooden or metal shield.", "Carrying a shield increases your Armor Class by 2. You can benefit from only one shield at a time."],
      isCustom: true,
      isDeleted: false,
    },
  },
  {
    label: "🥻 Light Armor (Leather)",
    value: "armor-light",
    data: {
      name: "Leather Armor",
      tier: "Common",
      weight: 8,
      cost: { quantity: 10, unit: "gp" },
      tags: ["armor", "light-armor", "leather"],
      description: ["Simple light armor fashioned from sturdy cured leather.", "Armor Class (AC) becomes 11 + your Dexterity modifier."],
      isCustom: true,
      isDeleted: false,
    },
  },
  {
    label: "🧥 Medium Armor (Scale Mail)",
    value: "armor-medium",
    data: {
      name: "Scale Mail",
      tier: "Common",
      weight: 45,
      cost: { quantity: 50, unit: "gp" },
      tags: ["armor", "medium-armor", "stealth-disadvantage"],
      description: ["This armor consists of a coat and leggings of leather covered with overlapping scales of metal.", "Armor Class (AC) becomes 14 + Dexterity modifier (max +2). Imposes disadvantage on Dexterity (Stealth) checks."],
      isCustom: true,
      isDeleted: false,
    },
  },
  {
    label: "🦾 Heavy Armor (Plate)",
    value: "armor-heavy",
    data: {
      name: "Plate Armor",
      tier: "Common",
      weight: 65,
      cost: { quantity: 1500, unit: "gp" },
      tags: ["armor", "heavy-armor", "plate", "stealth-disadvantage"],
      description: ["Plate consists of shaped, interlocking metal plates to cover the entire body.", "Armor Class (AC) is a flat 18. Requires a minimum Strength of 15 to wear and imposes disadvantage on Dexterity (Stealth) checks."],
      isCustom: true,
      isDeleted: false,
    },
  },
  {
    label: "💍 Ring of Protection (Wondrous)",
    value: "wondrous-ring",
    data: {
      name: "Ring of Protection",
      tier: "Rare",
      weight: 0,
      cost: { quantity: 2000, unit: "gp" },
      tags: ["ring", "wondrous", "attunement", "defense"],
      description: ["A simple gold ring engraved with runes of protection.", "While wearing this ring, you gain a +1 bonus to Armor Class (AC) and all saving throws. Requires attunement."],
      isCustom: true,
      isDeleted: false,
    },
  },
  {
    label: "✨ Wand of Magic Missiles (Wand)",
    value: "wondrous-wand",
    data: {
      name: "Wand of Magic Missiles",
      tier: "Uncommon",
      weight: 1,
      cost: { quantity: 350, unit: "gp" },
      tags: ["wand", "wondrous", "magic", "combat"],
      description: ["This wand has 7 charges.", "While holding it, you can use an action to expend 1 or more of its charges to cast the Magic Missile spell from it. The wand regains 1d6 + 1 expended charges daily at dawn."],
      isCustom: true,
      isDeleted: false,
    },
  },
  {
    label: "🎒 Bag of Holding (Wondrous Container)",
    value: "wondrous-container",
    data: {
      name: "Bag of Holding",
      tier: "Uncommon",
      weight: 15,
      cost: { quantity: 500, unit: "gp" },
      tags: ["bag", "container", "wondrous", "utility"],
      description: ["This bag has an interior space considerably larger than its outside dimensions.", "The bag can hold up to 500 pounds, not exceeding a volume of 64 cubic feet. The bag weighs 15 pounds regardless of its contents."],
      isCustom: true,
      isDeleted: false,
    },
  },
  {
    label: "🎯 Ammunition (20 Arrows)",
    value: "ammo-arrows",
    data: {
      name: "Arrows (20)",
      tier: "Common",
      weight: 1,
      cost: { quantity: 1, unit: "gp" },
      tags: ["ammunition", "ranged", "arrows"],
      description: ["A leather quiver containing 20 wooden arrows designed for shortbows and longbows."],
      isCustom: true,
      isDeleted: false,
    },
  },
  {
    label: "🍞 Rations (5 Days) (Consumable)",
    value: "food-rations",
    data: {
      name: "Rations (5 days)",
      tier: "Common",
      weight: 10,
      cost: { quantity: 25, unit: "sp" },
      tags: ["food", "consumable", "survival"],
      description: ["Compact, dry rations designed to sustain a traveler.", "Includes jerky, dried fruit, hardtack, and nuts. Enough food for 5 days of travel."],
      isCustom: true,
      isDeleted: false,
    },
  },
];
