export const quotes = [
  '"Fortune favors the bold... and the prepared." — Guild Proverb',
  '"Every blade remembers the hand that forged it."',
  '"Stars fall not in silence, but to light the path of explorers."',
  '"Knowledge is the sharpest weapon of them all."',
  '"Magic is not power — it is will given form."',
  '"A long rest is not a suggestion; it is a strategy."',
  '"Ask for advantage: clever plans beat lucky rolls."',
  '"Take the Help action. Teamwork is the best buff."',
  '"Light sources are weapons. Darkness is a monster."',
  '"Bonus actions are borrowed time—spend them."',
  '"If you don’t talk to NPCs, you are leaving treasure on the table."',
  '"Short rests are free healing. Use them before your hit dice expire."',
  '"Never split the party—unless you can teleport."',
  '"Grapples win boss fights; shove wins ledges."',
  '"The best initiative bonus is knowing what you want to do."',
  '"Carry chalk. Mazes fear geometry."',
  '"Talk to your DM; collaboration beats confrontation."',
  '"Silvered weapons: the cheapest insurance against were-things."',
  '"The rogue is not a trap detector. Ten-foot poles are."',
  '"A potion in hand is worth two in the backpack."',
  '"Always have a backup torch. And a backup character story."',
  '"Downtime is character growth—buy a contact, not just a sword."',
  '"Maps change. Lore doesn’t. Take notes."',
  '"The best roll is the friend you made in the tavern last session."',
  '"Being clever is fun; being clear helps your party."',
  '"A friendly NPC’s name is a quest hook in disguise."',
  '"When the DM asks “Are you sure?”, reconsider."',
  '"Leave breadcrumbs. Future you will thank you."',
  '"Spells end; consequences linger."',
  '"The bravest paladin knows when to retreat."',
  '"Don’t hoard consumables—victory is the best economy."',
  '"Ask what your character smells like. The world will feel real."',
  '"Remember: the story is co-written. Bring ideas, not demands."',
];
