import type { Character } from "./Character";
import { HeightLabel } from "./HeightLabel";

export const defaultCharacter: Character = {
  id: undefined,
  ownerId: undefined,
  imageUrl: "",
  name: "",
  isDead: false,
  isNPC: false,
  race: "",
  characterClass: "",
  background: "",
  level: 1,
  armorClass: 10,
  hitPoints: 10,
  maxHitPoints: 10,
  temporaryHitPoints: 0,
  speed: 30,
  initiative: 0,
  alignment: "",
  proficiencyBonus: 2,
  hitDice: "",
  proficiencies: [],
  languages: [],
  conditions: [],
  resistances: [],
  immunities: [],
  vulnerabilities: [],
  features: [],
  actions: [],
  spells: [],
  currencies: [],
  abilityScores: { str: 10, dex: 10, con: 10, int: 10, wis: 10, cha: 10 },
  savingThrows: {
    strength: 0,
    dexterity: 0,
    constitution: 0,
    intelligence: 0,
    wisdom: 0,
    charisma: 0,
  },
  inspiration: 0,
  skills: [
    { name: "Acrobatics", value: 0, proficient: false },
    { name: "Animal Handling", value: 0, proficient: false },
    { name: "Arcana", value: 0, proficient: false },
    { name: "Athletics", value: 0, proficient: false },
    { name: "Deception", value: 0, proficient: false },
    { name: "History", value: 0, proficient: false },
    { name: "Insight", value: 0, proficient: false },
    { name: "Intimidation", value: 0, proficient: false },
    { name: "Investigation", value: 0, proficient: false },
    { name: "Medicine", value: 0, proficient: false },
    { name: "Nature", value: 0, proficient: false },
    { name: "Perception", value: 0, proficient: false },
    { name: "Performance", value: 0, proficient: false },
    { name: "Persuasion", value: 0, proficient: false },
    { name: "Religion", value: 0, proficient: false },
    { name: "Sleight of Hand", value: 0, proficient: false },
    { name: "Stealth", value: 0, proficient: false },
    { name: "Survival", value: 0, proficient: false },
  ],
  spellSaveDc: 10,
  spellAttackBonus: 2,
  spellSlots: [
    { level: 1, current: 0, max: 0 },
    { level: 2, current: 0, max: 0 },
    { level: 3, current: 0, max: 0 },
    { level: 4, current: 0, max: 0 },
    { level: 5, current: 0, max: 0 },
    { level: 6, current: 0, max: 0 },
    { level: 7, current: 0, max: 0 },
    { level: 8, current: 0, max: 0 },
    { level: 9, current: 0, max: 0 },
  ],
  deathSavesSuccesses: 0,
  deathSavesFailures: 0,
  passivePerception: 10,
  passiveInvestigation: 10,
  passiveInsight: 10,
  experience: 0,
  carryingCapacity: 0,
  currentEncumbrance: 0,
  backstory: [],
  size: HeightLabel.MEDIUM,
  age: 20,
  height: "170 cm",
  weight: "70 kg",
  eyes: "",
  skin: "",
  hair: "",
  appearance: "",
  personalityTraits: "",
  ideals: "",
  bonds: "",
  flaws: "",
  notes: "",
  description: "",
  factionIds: [],
  inventoryIds: [],
  equipmentId: "",
  isDeleted: false,
};