import type { Character } from "./Character";
import { HeightLabel } from "./HeightLabel";

export const defaultCharacter = (): Character => ({
  name: "Unknown Traveler",
  isDead: false,
  isNPC: false,
  race: "Human",
  characterClass: "Fighter",
  background: "Folk Hero",
  level: 1,
  armorClass: 10,
  hitPoints: 10,
  maxHitPoints: 10,
  temporaryHitPoints: 0,
  speed: 30,
  initiative: 0,
  alignment: "Neutral",
  proficiencyBonus: 2,

  proficiencies: [],
  languages: ["Common"],
  conditions: [],
  resistances: [],
  immunities: [],
  vulnerabilities: [],
  features: [],
  actions: [],
  spells: [],
  currencies: [
    { type: "Silver", amount: 0, currencyCode: "sp" },
    { type: "Gold", amount: 0, currencyCode: "gp" },
  ],

  abilityScores: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
  },

  savingThrows: {
    strength: false,
    dexterity: false,
    constitution: false,
    intelligence: false,
    wisdom: false,
    charisma: false,
  },

  inspiration: 0,
  skills: {},
  spellSaveDc: 10,
  spellAttackBonus: 0,
  deathSavesSuccesses: 0,
  deathSavesFailures: 0,
  passivePerception: 10,
  passiveInvestigation: 10,
  passiveInsight: 10,
  experience: 0,
  carryingCapacity: 0,
  currentEncumbrance: 0,

  backstory: [],
  size: HeightLabel.MEDIUM,
  age: 25,
  height: `5'8"`,
  weight: "150 lbs",
  eyes: "Brown",
  skin: "Light",
  hair: "Black",
  appearance: "A nondescript individual.",
  personalityTraits: "Brave and loyal.",
  ideals: "Justice and honor.",
  bonds: "Family and friends.",
  flaws: "Impulsive and stubborn.",
  notes: "No additional notes.",
  description: "A brave adventurer.",

  factionIds: [],
  inventoryIds: [],
  equipmentId: "",
  isDeleted: false,
});