import type { Currency } from "./Currency";

export enum QuestType {
  Main = "Main",
  Side = "Side",
  Faction = "Faction",
  Personal = "Personal",
  Undefined = "Undefined"
}

export enum QuestStatus {
  Available = "Available",
  Unavailable = "Unavailable",
  Active = "Active",
  Completed = "Completed",
  Failed = "Failed"
}

export interface QuestObjective {
  id: string;                  // MongoDB ObjectId (generated by backend)
  description?: string;        // Short goal text
  isCompleted: boolean;        // True if objective has been finished
  currentProgress: number;     // Current numerical progress count
  completionThreshold: number; // Target numeric goal (defaults to 1)
}

export interface Quest {
  id?: string;                        // MongoDB ObjectId (generated by backend)
  campaignId: string;                 // Association with active Campaign
  involvedCharacterIds?: string[];    // Linked Character ObjectIds (used for Personal Quests)
  title: string;                      // Name of the quest
  description?: string;               // Lore, context, or notes
  location?: string;                  // Area, town, or plane name
  objectives: QuestObjective[];       // Embedded list of goals
  status: QuestStatus;                // Current state
  type: QuestType;                    // Type of quest
  rewardItemIds: string[];            // Loot items awarded
  rewardCurrencies: Currency[];         // Cash rewards list
  createdAt?: string;                 // ISO Date String (audited)
  updatedAt?: string;                 // ISO Date String (audited)
}
