export enum SectionColor {
  Blue = "blue",
  Cyan = "cyan",
  Teal = "teal",
  Green = "green",
  Lime = "lime",
  Yellow = "yellow",
  Orange = "orange",
  Red = "red",
  Pink = "pink",
  Grape = "grape",
  Violet = "violet",
  Indigo = "indigo",
  Gray = "gray",
  Dark = "dark",
  White = "white",
  Black = "black",
}
